'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default
    
    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager
    
    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''RadAjaxPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel2 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadAjaxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''btn0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn0 As Global.Telerik.Web.UI.RadPushButton
    
    '''<summary>
    '''approvalMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents approvalMsg As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''btnMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMgr As Global.Telerik.Web.UI.RadPushButton
    
    '''<summary>
    '''mgrMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mgrMsg As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''btnDummy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDummy As Global.Telerik.Web.UI.RadPushButton
    
    '''<summary>
    '''txtAcctLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcctLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''txtAcct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcct As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtIplanLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIplanLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''txtIplan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIplan As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''cmbPosLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPosLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''cmbPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPos As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''txtExpecLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpecLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''txtExpec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpec As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtPRLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPRLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''txtPR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPR As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''cmbRvwLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbRvwLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''cmbRvw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbRvw As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''chkPend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPend As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''chkRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRec As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''chkWO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWO As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''chkUnworked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUnworked As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''cmbIplnstLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbIplnstLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''cmbIplnst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbIplnst As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''cmbSrcLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSrcLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''cmbSrc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSrc As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''cmbClmLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbClmLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''cmbClm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbClm As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''cmbClmSLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbClmSLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''cmbClmS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbClmS As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''cmbActLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbActLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''cmbAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAct As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''cmbNxtLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNxtLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''cmbNxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNxt As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''cmbFActLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFActLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''cmbFAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFAct As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''cmbFNxtLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFNxtLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''cmbFNxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFNxt As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''chkPPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPPD As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''txtNPPDLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNPPDLabel As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''txtNPPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNPPD As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdd As Global.Telerik.Web.UI.RadEditor
    
    '''<summary>
    '''btnHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHelp As Global.Telerik.Web.UI.RadPushButton
    
    '''<summary>
    '''lblTimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimer As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''btnCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopy As Global.Telerik.Web.UI.RadPushButton
    
    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.Telerik.Web.UI.RadPushButton
End Class
